package Ventanas;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import java.awt.Image;
import java.awt.Toolkit;
/**
 *
 * @author yeiso
 */
public class Interfaz extends javax.swing.JFrame {
    
 
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        Divisas divisas = new Divisas();
        divisas.setSize(620, 280);
        divisas.setLocation(0, 0);
        
        Content.removeAll();
        Content.add(divisas, BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Iconos/Logo.png"));
        return retValue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Divisas = new javax.swing.JButton();
        jlbSalir = new javax.swing.JButton();
        Temperatura = new javax.swing.JButton();
        Content = new javax.swing.JPanel();
        jlbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Divisas.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Divisas.setForeground(new java.awt.Color(255, 255, 255));
        Divisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cambio.png"))); // NOI18N
        Divisas.setText("  Divisas");
        Divisas.setContentAreaFilled(false);
        Divisas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Divisas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cambio.png"))); // NOI18N
        Divisas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Cambio_42.png"))); // NOI18N
        Divisas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Divisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisasActionPerformed(evt);
            }
        });
        jPanel1.add(Divisas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 146, -1));

        jlbSalir.setBackground(new java.awt.Color(255, 255, 255));
        jlbSalir.setFont(new java.awt.Font("Yu Gothic UI", 2, 14)); // NOI18N
        jlbSalir.setForeground(new java.awt.Color(0, 0, 0));
        jlbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton.png"))); // NOI18N
        jlbSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jlbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlbSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jlbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 30, 30));

        Temperatura.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        Temperatura.setForeground(new java.awt.Color(255, 255, 255));
        Temperatura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/temperatura-alta.png"))); // NOI18N
        Temperatura.setText("  Temperatura");
        Temperatura.setContentAreaFilled(false);
        Temperatura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Temperatura.setInheritsPopupMenu(true);
        Temperatura.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/temperatura-alta.png"))); // NOI18N
        Temperatura.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/temperatura-alta (2) (1).png"))); // NOI18N
        Temperatura.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Temperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemperaturaActionPerformed(evt);
            }
        });
        jPanel1.add(Temperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 5, 200, 50));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel1.add(Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 620, 280));

        jlbFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPrincipal.jpg"))); // NOI18N
        jPanel1.add(jlbFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlbSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jlbSalirActionPerformed

    private void DivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisasActionPerformed
         Divisas divisas = new Divisas();
         ShowPanel(divisas);
    }//GEN-LAST:event_DivisasActionPerformed

    private void TemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemperaturaActionPerformed
        Temperatura temp = new Temperatura();
        ShowPanel(temp);
    }//GEN-LAST:event_TemperaturaActionPerformed

    private void ShowPanel(JPanel p) {
        
         p.setSize(620, 290);
         p.setLocation(0, 0);
        
         Content.removeAll();
         Content.add(p, BorderLayout.CENTER);
         Content.revalidate();
         Content.repaint();
    }
    
    
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JButton Divisas;
    private javax.swing.JButton Temperatura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbFondo;
    private javax.swing.JButton jlbSalir;
    // End of variables declaration//GEN-END:variables

}
